### ISSUE TITLE
Provide a COUNT function

### ISSUE THREAD

**Issue by martinthurn-LFT** [frezik/SQL-Functional#3]
Or at least add a Cookbook entry for how to accomplish COUNT()

**Comment by frezik** [comment]
Don't know how I missed adding COUNT(), but it's now implemented in v0.3.

**Comment by martinthurn-LFT** [comment]
Thank you so much!  Is it safe to assume that I can write COUNT(star)?  (Sorry I haven't downloaded and tried it yet)  
Perhaps add that to the documentation at least as an example?

**Comment by frezik** [comment]
Yup, `COUNT( star )` is how you'd do it. It technically would allow `COUNT([qw{ foo bar baz }])`, just because of how the implementation works out.
